input {
	kb_layout = latam

}


# --------------------------------------------------------
# HYPRLAND CONFIGURACIÓN PRINCIPAL (100% .conf)
# --------------------------------------------------------

source = ~/.config/hypr/configs/startup.conf
source = ~/.config/hypr/configs/looknfeel.conf
source = ~/.config/hypr/configs/windowrules.conf
source = ~/.config/hypr/configs/keybinds.conf
