# --------------------------------------------------------
# ATAJOS DE TECLADO
# --------------------------------------------------------

$mainMod = SUPER

# Aplicaciones del Sistema
bind = $mainMod, RETURN, exec, kitty
bind = $mainMod, E, exec, thunar
bind = $mainMod, SPACE, exec, rofi -show drun
bind = $mainMod, C, killactive, 
bind = $mainMod, M, exit, 
bind = $mainMod, B, exec, brave

# Gestión de Ventanas (Tiling)
bind = $mainMod, V, togglefloating, 
bind = $mainMod, P, pseudo, # dwindle

# Mover el foco entre ventanas (Flechas de dirección)
bind = $mainMod, H, movefocus, l
bind = $mainMod, L, movefocus, r
bind = $mainMod, K, movefocus, u
bind = $mainMod, J, movefocus, d

# Movel ventanas
bind = $mainMod SHIFT, H, movewindow, l
bind = $mainMod SHIFT, L, movewindow, r
bind = $mainMod SHIFT, K, movewindow, u
bind = $mainMod SHIFT, J, movewindow, d

# Cambiar de Workspace (Escritorios Virtuales del 1 al 5)
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5

# Mover ventana activa a un Workspace específico
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5

# Control de ventanas con el Mouse (Click Izquierdo/Derecho + Tecla Super)
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

# Bloquear la pantalla
bind = $mainMod CTRL, L, exec, hyprlock

# wlogout
bind = $mainMod, Escape, exec, wlogout

# Capturar toda la pantalla y guardarla en Screenshots
bind = , Print, exec, FILE=~/Screenshots/$(date +'%Y-%m-%d_%H-%M-%S').png && grim "$FILE" && swayimg "$FILE"

# Capturar un área seleccionada y guardarla en Screenshots
bind = SUPER, Print, exec, FILE=~/Screenshots/$(date +'%Y-%m-%d_%H-%M-%S').png && grim -g "$(slurp)" "$FILE" && notify-send "Captura Guardada" "Guardada en ~/Screenshots" -i "$FILE"

# Capturar un área seleccionada, guardarla temporalmente en Screenshots y abrir el editor Swappy
bind = $mainMod SHIFT, S, exec, grim -g "$(slurp)" - | swappy -f -

# Scripts
bind = SUPER, W, exec, ~/.config/hypr/scripts/cambiar_fondo.sh
