# --------------------------------------------------------
# AUTOARRANQUE DE APLICACIONES
# --------------------------------------------------------

# Agente de autenticación de políticas gráficas (Esencial)
exec-once = /usr/lib/polkit-kde-agent-1

# Fondo de pantalla (awww) y barra de estado (Waybar)
exec-once = awww-daemon
exec-once = ~/.config/hypr/configs/init-wallpaper.sh
exec-once = waybar
exec-once = mako
exec-once = swayosd-server
