# --------------------------------------------------------
# REGLAS DE VENTANAS (Sintaxis V2)
# --------------------------------------------------------

# Forzar a que las ventanas de diálogo y selección de archivos floten
windowrulev = float, title:^(Open File)(.*)$
windowrulev = float, title:^(Select a File)(.*)$
windowrulev = float, title:^(Choose wallpaper)(.*)$
windowrulev = float, title:^(File Operation Progress)(.*)$
windowrulev = opacity 1.0 override, class:^(kitty)$
windowrulev = blur, class:^(kitty)$
