# --------------------------------------------------------
# REGLAS DE VENTANAS (Sintaxis V2)
# --------------------------------------------------------

# Forzar a que las ventanas de diálogo y selección de archivos floten
windowrulev = float, title:^(Open File)(.*)$
windowrulev = float, title:^(Select a File)(.*)$
windowrulev = float, title:^(Choose wallpaper)(.*)$
windowrulev = float, title:^(File Operation Progress)(.*)$

# Forzar opacidad 100% sólida para Wofi (como ventana)
windowrulev = opacity 1.0 override 1.0 override, class:^(wofi)$
windowrulev = noblur, class:^(wofi)$
windowrulev = nodim, class:^(wofi)$

