# --------------------------------------------------------
# REGLAS DE VENTANAS (Sintaxis V2)
# --------------------------------------------------------

# Forzar a que las ventanas de diálogo y selección de archivos floten
windowrulev = float, title:^(Open File)(.*)$
windowrulev = float, title:^(Select a File)(.*)$
windowrulev = float, title:^(Choose wallpaper)(.*)$
windowrulev = float, title:^(File Operation Progress)(.*)$
# Forzar opacidad sólida absoluta en Rofi e impedir que el blur de Hyprland lo rompa
windowrulev = opacity 1.0 override 1.0 override, class:^(rofi)$
windowrulev = noblur, class:^(rofi)$
windowrulev = nodim, class:^(rofi)$
