# ~/.config/matugen/templates/kitty.conf

# Forzamos a que el fondo sea un Hex plano de 6 dígitos sin caracteres extraños
background #0f1417

# Kitty se encarga exclusivamente de la opacidad (60%)
background_opacity 0.25

# Permitir que el fondo sea dinámico
dynamic_background_opacity yes

# Resto de colores generados por Matugen (Limpios de espacios ocultos)
foreground #dfe3e7
cursor #8bd0ef
selection_background #40484c
selection_foreground #c0c8cd

# Paleta de colores ANSI
color0 #0f1417
color8 #40484c
color1 #ffb4ab
color9 #93000a
color2 #8bd0ef
color10 #004d64
color3 #c6c2ea
color11 #454364
color4 #b4cad6
color12 #354a53
color5 #116682
color13 #8a9297
color6 #8bd0ef
color14 #004d64
color7 #dfe3e7
color15 #c0c8cd
