# ~/.config/matugen/templates/kitty.conf

# Forzamos a que el fondo sea un Hex plano de 6 dígitos sin caracteres extraños
background #111418

# Kitty se encarga exclusivamente de la opacidad (60%)
background_opacity 0.25

# Permitir que el fondo sea dinámico
dynamic_background_opacity yes

# Resto de colores generados por Matugen (Limpios de espacios ocultos)
foreground #e1e2e8
cursor #a3c9fe
selection_background #43474e
selection_foreground #c3c6cf

# Paleta de colores ANSI
color0 #111418
color8 #43474e
color1 #ffb4ab
color9 #93000a
color2 #a3c9fe
color10 #1f4876
color3 #d9bde3
color11 #543f5e
color4 #bcc7db
color12 #3c4758
color5 #3a608f
color13 #8d9199
color6 #a3c9fe
color14 #1f4876
color7 #e1e2e8
color15 #c3c6cf
