# ~/.config/matugen/templates/kitty.conf

# Forzamos a que el fondo sea un Hex plano de 6 dígitos sin caracteres extraños
background #131318

# Kitty se encarga exclusivamente de la opacidad (60%)
background_opacity 0.25

# Permitir que el fondo sea dinámico
dynamic_background_opacity yes

# Resto de colores generados por Matugen (Limpios de espacios ocultos)
foreground #e4e1e9
cursor #bfc2ff
selection_background #46464f
selection_foreground #c7c5d0

# Paleta de colores ANSI
color0 #131318
color8 #46464f
color1 #ffb4ab
color9 #93000a
color2 #bfc2ff
color10 #3e4178
color3 #e8b9d4
color11 #5f3c52
color4 #c5c4dd
color12 #454559
color5 #565992
color13 #918f9a
color6 #bfc2ff
color14 #3e4178
color7 #e4e1e9
color15 #c7c5d0
